import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "../../components/HeroHeaderNav";

import { LoadingScreen } from "../../components/loading-screen";
import { BackgroundGrid } from "@/components/ui/background-grid";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased selection:bg-purple-100 selection:text-purple-900`}
      >
        <LoadingScreen>
          <BackgroundGrid />
          <main className="min-h-screen pt-20"> {/* Add padding for fixed header */}
              {children}
          </main>

        </LoadingScreen>
      </body>
    </html>
  );
}