const years = [
  "Year 1",
  "Year 2",
  "Year 3",
  "Year 4",
  "Year 5",
  "Year 6",
  "Year 7",
  "Year 8",
  "Year 9",
  "Year 10",
  "Year 11",
  "Year 12",
  "Year 13",
  "Year 14",
];

const coursesData = {
  "Year 1": [
    {
      id: "y1-earlystart",
      title: "SuperSheldon Early Start",
      type: "Early Skills / Entry Basics",
      duration: "",
      topics: 19,
      sales: 212,
      rating: 4.7,
      img: "/UK/courses/y11.jpg",
      brochure: "",
      path: "",
      desc: "An engaging introduction to foundational learning for young learners (Age 5–6). Focuses on early literacy, numeracy, and curiosity-building through interactive learning.",
      chapters: [
        { title: "Module 1" },
        { title: "Module 2" },
        { title: "Module 3" },
      ],
    },
  ],
  "Year 2": [
    {
      id: "y2-ks1sats",
      title: "SuperSheldon KS1 SATs Booster",
      type: "KS1 SATs Preparation",
      duration: "",
      topics: 25,
      sales: 178,
      rating: 4.3,
      img: "/UK/courses/y21.jpg",
      brochure: "",
      path: "",
      desc: "Targeted preparation for KS1 SATs with engaging exercises in English and Maths to build exam confidence and key skills for future success.",
      chapters: [
        { title: "Module 1" },
        { title: "Module 2" },
        { title: "Module 3" },
      ],
    },
  ],
  "Year 3": [
    {
      id: "y3-7plus",
      title: "SuperSheldon 7+ Prep",
      type: "Independent School Entry Preparation",
      duration: "",
      topics: 14,
      sales: 239,
      rating: 4.8,
      img: "/UK/courses/y31.jpg",
      brochure: "",
      path: "",
      desc: "Comprehensive preparation for 7+ entrance exams, focusing on literacy, reasoning, and early problem-solving techniques.",
      chapters: [
        { title: "Module 1" },
        { title: "Module 2" },
        { title: "Module 3" },
      ],
    },
    {
      id: "y3-8plus",
      title: "SuperSheldon 8+ Advantage",
      type: "Independent School Entry Preparation",
      duration: "",
      topics: 20,
      sales: 172,
      rating: 4.5,
      img: "/UK/courses/y32.jpg",
      brochure: "",
      path: "",
      desc: "Designed for students aiming for 8+ independent school entry, this course builds analytical thinking and advanced comprehension skills.",
      chapters: [
        { title: "Module 1" },
        { title: "Module 2" },
        { title: "Module 3" },
      ],
    },
  ],
  "Year 4": [
    {
      id: "y4-9plus",
      title: "SuperSheldon 9+ Mastery",
      type: "Selective Entry Exam Preparation",
      duration: "",
      topics: 17,
      sales: 360,
      rating: 4.6,
      img: "/UK/courses/y41.jpg",
      brochure: "",
      path: "",
      desc: "Advanced preparation for 9+ selective school entry exams with focused modules on comprehension, reasoning, and applied maths.",
      chapters: [
        { title: "Module 1" },
        { title: "Module 2" },
        { title: "Module 3" },
      ],
    },
  ],
  "Year 5": [
    {
      id: "y5-10plus",
      title: "SuperSheldon 10+ Success",
      type: "Selective School Preparation",
      duration: "",
      topics: 29,
      sales: 312,
      rating: 4.9,
      img: "/UK/courses/y61.jpg", // Use the same image
      brochure: "",
      path: "",
      desc: "Develops advanced problem-solving and reasoning skills to prepare for 10+ selective school exams with confidence and strategy.",
      chapters: [
        { title: "Module 1" },
        { title: "Module 2" },
        { title: "Module 3" },
      ],
    },
  ],
  "Year 6": [
    {
      id: "y6-11plus",
      title: "SuperSheldon 11+ Success",
      type: "Grammar & Independent School Exam Preparation",
      duration: "",
      topics: 28,
      sales: 372,
      rating: 4.5,
      img: "/UK/courses/y61.jpg",
      brochure: "",
      path: "",
      desc: "Comprehensive preparation for 11+ Grammar and Independent School entrance exams, covering verbal, non-verbal, maths, and English reasoning.",
      chapters: [
        { title: "Module 1" },
        { title: "Module 2" },
        { title: "Module 3" },
      ],
    },
    {
      id: "y6-ks2sats",
      title: "SuperSheldon KS2 SATs Power",
      type: "SATs Exam Preparation",
      duration: "",
      topics: 26,
      sales: 318,
      rating: 4.1,
      img: "/UK/courses/y62.jpg",
      brochure: "",
      path: "",
      desc: "Focused revision and practice for KS2 SATs, ensuring mastery of key concepts in English, maths, and reasoning for high attainment.",
      chapters: [
        { title: "Module 1" },
        { title: "Module 2" },
        { title: "Module 3" },
      ],
    },
  ],
  "Year 7": [
    {
      id: "y7-foundation",
      title: "SuperSheldon KS3 Foundation Boost",
      type: "KS3 Transition",
      duration: "",
      topics: 16,
      sales: 276,
      rating: 4.4,
      img: "/UK/courses/y71.jpg",
      brochure: "",
      path: "",
      desc: "Smooth transition from KS2 to KS3 with strong foundations in English, maths, and science through engaging and challenging lessons.",
      chapters: [
        { title: "Module 1" },
        { title: "Module 2" },
        { title: "Module 3" },
      ],
    },
  ],
  "Year 8": [
    {
      id: "y8-13plus",
      title: "SuperSheldon 13+ Common Entrance Mastery",
      type: "13+ Entrance Preparation",
      duration: "",
      topics: 22,
      sales: 315,
      rating: 4.2,
      img: "/UK/courses/y81.jpg",
      brochure: "",
      path: "",
      desc: "Rigorous preparation for 13+ Common Entrance Exams, focusing on English, maths, and reasoning at an advanced level.",
      chapters: [
        { title: "Module 1" },
        { title: "Module 2" },
        { title: "Module 3" },
      ],
    },
    {
      id: "y8-case",
      title: "SuperSheldon 13+ Scholarship Edge (CASE)",
      type: "Scholarship Preparation",
      duration: "",
      topics: 19,
      sales: 224,
      rating: 4.8,
      img: "/UK/courses/y82.jpg",
      brochure: "",
      path: "",
      desc: "A high-performance course designed for students targeting scholarships or competitive entry exams through analytical depth and mastery.",
      chapters: [
        { title: "Module 1" },
        { title: "Module 2" },
        { title: "Module 3" },
      ],
    },
  ],
  "Year 9": [
    {
      id: "y9-progress",
      title: "SuperSheldon KS3 Progress Builder",
      type: "KS3 Consolidation / GCSE Foundation",
      duration: "",
      topics: 21,
      sales: 181,
      rating: 4.3,
      img: "/UK/courses/y91.jpg",
      brochure: "",
      path: "",
      desc: "Consolidate KS3 learning and begin GCSE foundations with focused modules in core subjects to build confidence for upcoming exams.",
      chapters: [
        { title: "Module 1" },
        { title: "Module 2" },
        { title: "Module 3" },
      ],
    },
  ],
  "Year 10": [
    {
      id: "y10-gcsecore",
      title: "SuperSheldon GCSE Core Prep",
      type: "GCSE Preparation",
      duration: "",
      topics: 23,
      sales: 360,
      rating: 4.9,
      img: "/UK/courses/y101.jpg", //from here on, no image is correct
      brochure: "",
      path: "",
      desc: "Strong foundation in GCSE core subjects — English, Maths, and Science — through targeted lessons and structured practice.",
      chapters: [
        { title: "Module 1" },
        { title: "Module 2" },
        { title: "Module 3" },
      ],
    },
  ],
  "Year 11": [
    {
      id: "y11-fasttrack",
      title: "SuperSheldon GCSE Fast-Track Success",
      type: "GCSE Final Exam Preparation",
      duration: "",
      topics: 26,
      sales: 374,
      rating: 4.7,
      img: "/UK/courses/y101.jpg",
      brochure: "",
      path: "",
      desc: "Final-year revision and accelerated strategies for high GCSE performance with intensive coverage of all major subjects.",
      chapters: [
        { title: "Module 1" },
        { title: "Module 2" },
        { title: "Module 3" },
      ],
    },
    {
      id: "y11-igcse",
      title: "SuperSheldon iGCSE Global Advantage",
      type: "iGCSE Preparation",
      duration: "",
      topics: 29,
      sales: 356,
      rating: 4.8,
      img: "/UK/courses/y101.jpg",
      brochure: "",
      path: "",
      desc: "Comprehensive iGCSE preparation across subjects with an emphasis on global perspectives, critical thinking, and exam strategies.",
      chapters: [
        { title: "Module 1" },
        { title: "Module 2" },
        { title: "Module 3" },
      ],
    },
  ],
  "Year 12": [
    {
      id: "y12-as",
      title: "SuperSheldon AS Level Builder",
      type: "AS/A-Level Start",
      duration: "",
      topics: 18,
      sales: 280,
      rating: 4.4,
      img: "/UK/courses/y101.jpg",
      brochure: "",
      path: "",
      desc: "Start A-Level journey with foundational modules to ensure a strong understanding of advanced topics and exam readiness.",
      chapters: [
        { title: "Module 1" },
        { title: "Module 2" },
        { title: "Module 3" },
      ],
    },
  ],
  "Year 13": [
    {
      id: "y13-al",
      title: "SuperSheldon A-Level Success",
      type: "A-Level & University Entrance",
      duration: "",
      topics: 24,
      sales: 368,
      rating: 4.9,
      img: "/UK/courses/y101.jpg",
      brochure: "",
      path: "",
      desc: "Final preparation for A-Levels and competitive university entrance exams, including Oxbridge preparation, UCAS applications, and specialist pathways.",
      chapters: [
        { title: "Module 1" },
        { title: "Module 2" },
        { title: "Module 3" },
      ],
    },
  ],
  "Year 14": [
    {
      id: "y14-special",
      title: "SuperSheldon Specialist Pathways",
      type: "Medicine / Law / Economics & Maths Prep",
      duration: "",
      topics: 30,
      sales: 380,
      rating: 5.0,
      img: "/UK/courses/y101.jpg",
      brochure: "",
      path: "",
      desc: "Specialist courses tailored for students preparing for competitive tests such as UCAT, BMAT, LNAT, TMUA, STEP, and MAT, along with bespoke university application guidance.",
      chapters: [
        { title: "Module 1" },
        { title: "Module 2" },
        { title: "Module 3" },
      ],
    },
  ],
};

export { years, coursesData };