name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            source ~/.nvm/nvm.sh
            nvm use 24.19.0

            cd ~/revamp/Website_Revamp
            git pull origin main

            cd Backend
            npm install

            pm2 restart revamp-backend
